### PR TITLE
Add run_command API endpoint

### PR DESCRIPTION
**Pull request by PunKeel**
Arguments: 
- command: the command to run. Might have multiple lines.

### CODE REVIEW

**Comment by sibprogrammer** [comment]
Please squash commits before pull request. Bunch of commits with meaningless messages is a problem for future code maintenance.

**Comment by PunKeel** [comment]
Hi,

Indeed! Was just waiting to test it properly before squashing. (and it
seems to be OK, so I'll squash them later today)

Thanks

**Comment by PunKeel** [comment]
Done !

**Comment by sibprogrammer** [comment]
A little bit re-worked code was committed. See daa9d42438fade4cb432eee7d6820994611787f1

**Comment by PunKeel** [comment]
Great! Thank you :)

**Pull request closed without merging**
